### ISSUE TITLE
Gas meter not updating

### ISSUE THREAD

**Issue by zeuslooye** [gruijter/com.plugwise.smile#11]
Hello, my P1 is not updating the gas meter ani more sinds 8-8

Can you help?
Gr Jeroen (NL)

**Comment by gruijter** [comment]
I would need more data to help you. That will get pretty technical though..

Would you be able to:
1) install Node on a PC
2) install the smilep1 package: `npm i smilep1`
3 ) run a test: `npm test id=yourDeviceID`
4) post the result here

See: https://www.npmjs.com/package/smilep1

**Comment by zeuslooye** [comment]
Sorry but I can’t get node to work on my Mac and it even won’t work on my synology. 
Is there anything else I can do
