### ISSUE TITLE
Install fails on first incorrect smile ID

### ISSUE THREAD

**Issue by maja2020** [gruijter/com.plugwise.smile#12]
Homey: 3.0.0, appversion 3.0.5

I tried to install a Plugwise P1 v3 smartmeter, but it failed because I entered a wrong ID. 
You can alter the smile id and try again, but it fails again and the again, I am sure I used the right ID the second time and later. 
A retry (with restart) of the installation wizzard succeeded. It fixed the problem for me. 

Nothing urgent, I expected the app to either retry with newly entered smile ID or abort the installation.

**Comment by gruijter** [comment]
Thx 4 reporting! I will look into this.
