### ISSUE TITLE
Time out error

### ISSUE THREAD

**Issue by Peter0987** [gruijter/com.plugwise.smile#13]
HI Robin, thanks for the app. 

Unfortunately I get a time out error and afterwards a comment that it could not find that pairsession.

I have plugged in the P1 in lan and the p1 and the plugwise home app works, however I can't seem to connect it to the homey. Do you know why? thanks in advance!
Kind regards
Peter

**Comment by gruijter** [comment]
Can you create a diagnostics report pls

**Comment by Peter0987** [comment]
thank you the nr is 
22260E

**Comment by gruijter** [comment]
I meant an app diagnostics report 🙃

**Comment by Peter0987** [comment]
oops sorry! How do I do that?

**Comment by gruijter** [comment]
From the app settings

**Comment by Peter0987** [comment]
found it:
2021-05-28 16:42:00 [err] Pair error Error: connect
ETIMEDOUT 192.168.0.97:80 at TCPConnectWrap.afterConnect [as oncomplete]
(net.js:1137:16){ errno: 'ETIMEDOUT', code: 'ETIMEDOUT',
syscall: 'connect', address: '192.168.0.97' port: 80 }

**Comment by gruijter** [comment]
What happens if you enter that ip address in your webbrowser?

**Comment by Peter0987** [comment]
i get the login

**Comment by Peter0987** [comment]
i'm asked for a username and password, but i don't which one

**Comment by Peter0987** [comment]
managed to login. so that works

**Comment by gruijter** [comment]
Mmh. How long after you enter the ip does it take to get the login screen?

By the way: username is smile, password is the id from the sticker on the device.

And it is a Smile P1, not a Smile?

**Comment by Peter0987** [comment]
Directly and indeed it is a smile p1.


Op vr 28 mei 2021 om 17:13 schreef gruijter ***@***.***>

**Comment by gruijter** [comment]
Ok, will try to reproduce tonight but I'm not sure what is going on.

What is your homey fw level, app level and smile fw level?

**Comment by gruijter** [comment]
I have tried removing the app, installed the latest version from the app store (3.1.0). Added my Smile P1 from my Android phone. And it worked immediately...

I then upgraded the smiles fw to version 4.1.3. And did all the above again.
And again it worked immediately.

I also tried adding it from a browser: https://tools.developer.homey.app/tools/pair
Also there no problem at all.

So I don't know what is going on. You might still want to send me a full app diagnostics report after you try to pair (I never received this from you).

**Comment by Peter0987** [comment]
Hi that is strange.

2021-05-29 17:20:59 [err] Pair error Error: connect ETIMEDOUT
192.168.0.97:80 at TCPConnectWrap.afterConnect [as oncomplete]
(net.js:1137:16) { errno: 'ETIMEDOUT', code: 'ETIMEDOUT', syscall:
'connect', address: '192.168.0.97', port: 80 }
2021-05-29 17:20:24 [err] Pair error Error: connect ETIMEDOUT
192.168.0.97:80 at TCPConnectWrap.afterConnect [as oncomplete]
(net.js:1137:16) { errno: 'ETIMEDOUT', code: 'ETIMEDOUT', syscall:
'connect', address: '192.168.0.97', port: 80 }
2021-05-29 17:18:46 [log] save button pressed in frontend
2021-05-29 17:18:12 [log] save button pressed in frontend
2021-05-29 17:17:19 [log] smile_power ledring screensaver ready!
2021-05-29 17:17:16 [log] entering SmileP1 driver
2021-05-29 17:17:16 [log] capturing stderr
2021-05-29 17:17:16 [log] capturing stdout

I also reinstalled the app from the App Store but still didn’t work.





Op za 29 mei 2021 om 17:11 schreef gruijter ***@***.***>

**Comment by gruijter** [comment]
Pls press on the button `Create Diagnostics Report` in the app settings

**Comment by Peter0987** [comment]
Sorry you mean from the homey app or the Plugwise app? I can create an
diagnostic report Id for the homey app. But I can only find a log button I
the Plugwise app



Op za 29 mei 2021 om 17:27 schreef gruijter ***@***.***>

**Comment by Peter0987** [comment]
Morning

The report link is

4763b6bc-8b1c-4f81-8953-34d080897481

Thx
Peter

Op za 29 mei 2021 om 17:27 schreef gruijter ***@***.***>

**Comment by gruijter** [comment]
Got it. And the firmware levels of Homey and Smile are?

**Comment by Peter0987** [comment]
Homey 6.1.0
Plugwise 3.1.0

Op ma 31 mei 2021 om 07:42 schreef gruijter ***@***.***>

**Comment by gruijter** [comment]
Smile firmware level 🤣

**Comment by Peter0987** [comment]
haha that is 4.1.4

Op ma 31 mei 2021 om 08:17 schreef gruijter ***@***.***>:

**Comment by gruijter** [comment]
that is interesting. Mine is at 4.1.3 and unable to upgrade to 4.1.4.

How did you get it to upgrade to 4.1.4?

**Comment by Peter0987** [comment]
via the plugwisehome app.
and that app works well.


Op ma 31 mei 2021 om 14:01 schreef gruijter ***@***.***>:

**Comment by gruijter** [comment]
Well, I'm definitely stuck at 4.1.3.

Do you know how to do port forwarding in your router? If so I would like to have remote access to your Smile to do further investigations.
