### ISSUE TITLE
Plugwise P1 EHOSTREACH error

### ISSUE THREAD

**Issue by MHerweijer** [gruijter/com.plugwise.smile#14]
Homey cannot connect to the Plugwise P1 anymore. I tried rebooting Homey and the P1 but still I get the message “connect EHOSTREACH 192.168.0.185”. 
The Plugwise app works like a charm and also Home assistant can connect to the P1. 

I already created a diagn. Report. 
155f3a8b-6554-4042-94df-fc163f9c638e

Br. Marcel

**Comment by gruijter** [comment]
do you still have this issue?

**Comment by MHerweijer** [comment]
Hi,

After de installation and installing the P1 app en device in homey everything is working smoothly again. 

Br. Marcel


Verstuurd vanaf mijn iPhone
