### ISSUE TITLE
No more MQTT data with version 4.0.0 of P1 App

### ISSUE THREAD

**Issue by stofferr** [gruijter/com.plugwise.smile#15]
Hi Robin,

Since this version 4.0.0, the MQTT hub does not receive any MQTT events from this app. The app itself seems to be working. I can see smart meter data being updated.

I am aware that this app is not the MQTT Hub app. But this app was updated in my Homey and now my MQTT dashboards don't update anymore. 

I have updated all other apps. I have updates my node red and node red dashboards. I have updated all components on the dashboard. I can see other updates arriving from Homey, except for P1 data. 

Would you be able to help investigate please?

Roger

**Comment by stofferr** [comment]
Hi Robin,
I'm not sure it's the Plugiwse Smile app anymore. Turns out the update happened yesterday afternoon and the updates were still broadcasted to MQTT. After a spontaneous reboot of Homey at 2am today morning the updates stopped.
I have restarted Homey manually today and it did not resolve the issue.
Still investigating...
Roger

**Comment by gruijter** [comment]
Ok. keep me posted. Not sure how MQTT hub is getting its data. I basically only migrated to SDK3, and did not change the names of the capabilities. Try contacting the dev of MQTT hub (@harrydegroot)

**Comment by stofferr** [comment]
Thanks, I created an issue in the MQTT Hub app repos as well: https://github.com/harriedegroot/nl.hdg.mqtt/issues/70

**Comment by stofferr** [comment]
Solved without understanding why - I changed nothing.....
