### ISSUE TITLE
P1 socket hang up

### ISSUE THREAD

**Issue by erwtje77** [gruijter/com.plugwise.smile#19]
Hoi Robin,
De app voor de smile p1 crashed constant sinds vandaag 31-1-22 onderstaand nr is van ingestuurd diagnostic rapport kun je mij vertellen wat er mis gaat en wat te doen

064c4b6b-cb4d-416f-8136-e3e606c9db42

Groet Erwin

**Comment by gruijter** [comment]
_Poll error socket hang up_

Geeft aan netwerk problemen of dat je smile hangt. Is er iets veranderd in je netwerk? Of heb je firmware geupgrade? Reboot van router, smile en Homey kan helpen.
Je kunt ook proberen de polltime langer te zetten (bijvoorbeeld 60s). De kans op socket hang up neemt dan af.

**Comment by erwtje77** [comment]
Hoi probleem heeft zichzelf opgelost na reboot van homey werkt nu weer naar behoren in ieder geval bedankt voor de reactie 
-------- Oorspronkelijk bericht --------Van: gruijter ***@***.***> Datum: 02-02-2022  21:21  (GMT+01:00) Aan: "gruijter/com.plugwise.smile" ***@***.***> Cc: erwtje77 ***@***.***>, Author ***@***.***> Onderwerp: Re: [gruijter/com.plugwise.smile] P1 socket hang up (Issue #19) 
Poll error socket hang up
Geeft aan netwerk problemen of dat je smile hangt. Is er iets veranderd in je netwerk? Of heb je firmware geupgrade? Reboot van router, smile en Homey kan helpen.
Je kunt ook proberen de polltime langer te zetten (bijvoorbeeld 60s). De kans op socket hang up neemt dan af.
