### ISSUE TITLE
Socket hang up error after reboot of router

### ISSUE THREAD

**Issue by Itriz** [gruijter/com.plugwise.smile#22]
After a reboot of my KPN Experia V10 router, the plugwise smile app in Homey gets disconnected and shows an error (socket hang up). A restart of the app in Homey does not solve the problem. The only way out that I found was to de-install the app and re-install the app again. Add my plugwise smile device again (and repair all flows with variables of the plugwise smile). Is there a way to prevent this from happening after a reboot of my router?

**Comment by gruijter** [comment]
You probably didnt set a fixed ip address for the smile in the router. On router reboot chances are the ip address of the smile changes and Homey cannot find it anymore.

**Comment by Itriz** [comment]
Thanks for your reply. IP address was not fixed indeed. Will change this, problem solved.
