### ISSUE TITLE
After update to v5.0.0 the screensaver is gone

### ISSUE THREAD

**Issue by nvgerwen** [gruijter/com.plugwise.smile#26]
The P1 powerusage ledring screensaver cannot be found

**Comment by ruudvaneck** [comment]
just migrated from Homey pro 2019 to 2023 and ledring powerusage is not working on 2023

**Comment by gruijter** [comment]
Correct. You obviously didnt know this when you bought the hp2023. Speaker is also gone ;)

**Comment by ruudvaneck** [comment]
To bad! 

 

Was een mooie extra gadget. Had je mooi gemaakt. Jammer dat hij niet meer werkt.  

 

 

Met vriendelijke groet, 

 

Ruud van Eck

Markt 39 

5521 AK  Eersel 

***@***.***

0616610003

 

Van: gruijter ***@***.***> 
Verzonden: maandag 29 januari 2024 16:56
Aan: gruijter/com.plugwise.smile ***@***.***>
CC: Ruud van Eck ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [gruijter/com.plugwise.smile] After update to v5.0.0 the screensaver is gone (Issue #26)

 

Correct. You obviously didnt know this when you bought the hp2023. Speaker is also gone ;)
