### ISSUE TITLE
Verschil tussen Gasmeter in de app en de waarde die ik uitlees met mijn homey.

### ISSUE THREAD

**Issue by AbNetten** [gruijter/com.plugwise.smile#28]
Ik heb een verschil tussen Gasmeter in de app en de waarde die ik uitlees met mijn homey. 
Ik zie het verschil alleen bij gasmeter.  In de app 4455,74, in homey 4452,21

Ik heb in Homey de app al herstart, dat was geen oplossing.

**Comment by gruijter** [comment]
En wat zegt je gasmeter zelf?

**Comment by AbNetten** [comment]
De gasmeter geeft hetzelfde aan als de plugwise app. (4457,79)

In Homey krijg ik nog steeds de waarde 4452.21, het lijkt er op dat de waarde al meerdere dagen niet geupdate wordt.
Als ik mijn verbruik bekijk is de waarde sinds 27-06-2023 niet meer bijgewerkt.

Ab Netten




------ Oorspronkelijke bericht ------
Van "gruijter" ***@***.******@***.***>>
Aan "gruijter/com.plugwise.smile" ***@***.******@***.***>>
CC "AbNetten" ***@***.******@***.***>>; "Author" ***@***.******@***.***>>
Datum 6-7-2023 19:24:19
Onderwerp Re: [gruijter/com.plugwise.smile] Verschil tussen Gasmeter in de app en de waarde die ik uitlees met mijn homey. (Issue #28)


En wat zegt je gasmeter zelf?

**Comment by gruijter** [comment]
Ik neem aan dat je Homey al hebt gereboot?

Wat zie je in de app log?

**Comment by AbNetten** [comment]
Hallo,

Ik zie nu dat ook de andere waardes niet meer bijgewerkt worden.


Ab Netten


------ Oorspronkelijke bericht ------
Van "Ab Netten" ***@***.******@***.***>>
Aan "gruijter/com.plugwise.smile" ***@***.******@***.***>>
Datum 7-7-2023 16:17:22
Onderwerp Re[2]: [gruijter/com.plugwise.smile] Verschil tussen Gasmeter in de app en de waarde die ik uitlees met mijn homey. (Issue #28)

De gasmeter geeft hetzelfde aan als de plugwise app. (4457,79)

In Homey krijg ik nog steeds de waarde 4452.21, het lijkt er op dat de waarde al meerdere dagen niet geupdate wordt.
Als ik mijn verbruik bekijk is de waarde sinds 27-06-2023 niet meer bijgewerkt.

Ab Netten




------ Oorspronkelijke bericht ------
Van "gruijter" ***@***.******@***.***>>
Aan "gruijter/com.plugwise.smile" ***@***.******@***.***>>
CC "AbNetten" ***@***.******@***.***>>; "Author" ***@***.******@***.***>>
Datum 6-7-2023 19:24:19
Onderwerp Re: [gruijter/com.plugwise.smile] Verschil tussen Gasmeter in de app en de waarde die ik uitlees met mijn homey. (Issue #28)


En wat zegt je gasmeter zelf?

**Comment by AbNetten** [comment]
Homey gereboot.

***@***.***


------ Oorspronkelijke bericht ------
Van "gruijter" ***@***.******@***.***>>
Aan "gruijter/com.plugwise.smile" ***@***.******@***.***>>
CC "AbNetten" ***@***.******@***.***>>; "Author" ***@***.******@***.***>>
Datum 7-7-2023 16:21:46
Onderwerp Re: [gruijter/com.plugwise.smile] Verschil tussen Gasmeter in de app en de waarde die ik uitlees met mijn homey. (Issue #28)


Ik neem aan dat je Homey al hebt gereboot?

Wat zie je in de app log?

**Comment by AbNetten** [comment]
Ik heb alles van de plugwise verwijderd en opnieuw geinstalleerd.
Werkt nu weer prima.


------ Oorspronkelijke bericht ------
Van "Ab Netten" ***@***.******@***.***>>
Aan "gruijter/com.plugwise.smile" ***@***.******@***.***>>
Datum 7-7-2023 16:39:44
Onderwerp Re[2]: [gruijter/com.plugwise.smile] Verschil tussen Gasmeter in de app en de waarde die ik uitlees met mijn homey. (Issue #28)

Homey gereboot.

***@***.***


------ Oorspronkelijke bericht ------
Van "gruijter" ***@***.******@***.***>>
Aan "gruijter/com.plugwise.smile" ***@***.******@***.***>>
CC "AbNetten" ***@***.******@***.***>>; "Author" ***@***.******@***.***>>
Datum 7-7-2023 16:21:46
Onderwerp Re: [gruijter/com.plugwise.smile] Verschil tussen Gasmeter in de app en de waarde die ik uitlees met mijn homey. (Issue #28)


Ik neem aan dat je Homey al hebt gereboot?

Wat zie je in de app log?

**Comment by gruijter** [comment]
Ik vermoed dat het ip adres was veranderd.
Anyhoe  mooi dat het werkt
