### ISSUE TITLE
Daily or hourly data

### ISSUE THREAD

**Issue by martin072** [gruijter/com.plugwise.smile#29]
Hi, 

Maybe i've missed it (still getting to know Homey..) but I can only see cumulative data (except for the currently used power). 
All insight variables are mostly cumulative, and not usage per hour for example. 

Is there anyway to generate/see  data based on intervals?
ie. if I look at "Produced High" it only show cumulative data, not data from today, last week etc.

**Comment by gruijter** [comment]
Homey doesn't have that.
But I created another app to do that for you!

https://homey.app/en-us/app/com.gruijter.powerhour/Power-by-the-Hour/

Don't forget to support the developers of the apps you use 😉

**Comment by martin072** [comment]
> Homey doesn't have that. But I created another app to do that for you!
> 
> https://homey.app/en-us/app/com.gruijter.powerhour/Power-by-the-Hour/
> 
> Don't forget to support the developers of the apps you use 😉

Ahh, totally missed that option, will look into it! Thanks
