### ISSUE TITLE
Ledring doesn't work in Homey V2

### ISSUE THREAD

**Issue by nhassink** [gruijter/com.plugwise.smile#6]
The ledring screensaver doesn't work anymore under v2. It still shows up in the list of screensavers, but when you select it the screensaver does not change.

**Comment by gruijter** [comment]
Thx for reporting. I have ordered a Homey to be able to do testing for V2. I will investigate this. But so many apps to test, so little time... It might take some time, stay tuned 🤗

**Comment by hans70** [comment]
I'm having the same issue. Hereby confirmed the screensaver is broken in V2. Screensaver defaults to the rainbow screensaver.

**Comment by veulemj1** [comment]
Here the same issue. Hopefully it is a simple change in the code :-)

**Comment by gruijter** [comment]
Version 2.1.0 should fix it. Could anyone test?

**Comment by veulemj1** [comment]
Hello Robin,

I have looked for the update, but cold find him in the app-store. So did a deinstall and tried to reinstall. But the install crashes with a checksum error. Without error code. Wie de can we find the update?

Regards 
Jo

**Comment by gruijter** [comment]
You can sideload it if you follow these instructions: https://community.athom.com/t/how-to-cli-install-method/198

Otherwise you have to wait for the appstore release :)

**Comment by veulemj1** [comment]
I did the install over Node-CLI from version V2.1.0 and restart the Homey. But the issue with the LED-ring is still there. There is no respond, the LEDring is showing the Spectrum ambiance. Normally was the ring green with a little red dot turning around and when there was a change in use of energy the ring get more red.

**Comment by gruijter** [comment]
Ok, thx for testing. I can further investigate this Homey V2 issue once I receive the test Homey that I ordered from Athom. It will take some weeks though.

**Comment by veulemj1** [comment]
Robin,

After update Homey version 2.0.2-rc.2 is the LEDring working for me.
So I think it wasn't something in you're app but in the source of the Homey.

Regards,
Jo
