### ISSUE TITLE
New plugwise P1 firmware doesnt work with homey anymore

### ISSUE THREAD

**Issue by eelco2k** [gruijter/com.plugwise.smile#7]
Unfortunately the new firmware which plugwise released for the plugwise P1 will not work with the Homey app anymore.

Firmware version: v3.3.5

You need to use their “plugwise home” (blue P app icon) app now as well. Instead of the dedicated plugwise app for the P1 (the brown yellow app icon). 

So perhaps they combined that API. So that they can also use the plugs, adam, lisa and now also the P1 in the same app.

**Comment by eelco2k** [comment]
I checked the code really fast:

The smileP1.js does a request to the ip of thr device and in this direcory:

const meterPath = '/core/modules';

But when i view this map on my device: i get non vital info: only:

Plugwise Gateway AME Smile 2.0 board Etc etc some dates and type of connection

The link /core/domain_objects do still give me some info: example:

ectricity_consumed Wh 2019-06-09T00:30:00+02:00 3161826.00 5527251.00 2019-06-09T00:39:22+02:00 electricity_produced W 2019-06-08T19:21:44+02:00 0.00 0.00 2019-06-09T00:39:22+02:00 electricity_consumed W 2019-06-09T00:39:20+02:00 0.00 385.00 2019-06-08T23:00:00+02:00 gas_consumed m3 2019-06-08T23:00:00+02:00 PT1H 0.00 2019-06-09T00:35:00+02:00 gas_consumed m3 2019-06-09T00:35:00+02:00 2161.70 2019-06-09T00:15:00+02:00 electricity_produced Wh 2019-06-09T00:15:00+02:00 PT15M 0.00 0.00 2019-06-09T00:30:00+02:00 electricity_produced Wh 2019-06-09T00:30:00+02:00 794394.00 393923.00 2019-06-09T00:15:00+02:00 electricity_consumed Wh 2019-06-09T00:15:00+02:00 PT15M 0.00 82.00

**Comment by gruijter** [comment]
Do you have the current Smile P1, or the old one? I have the old one , and it is still on the firmware 2.1.13. I do not see anything about a firmware upgrade.  I also installed the plugwise home app, but that only works with a plugwise bridge (that I dont have).

I tried googling for any news on new firmware or a changed interface, but cannot find anything on this topic. I will send a info request to plugwise and see if they are willing to shed some light on this.

In the mean time, if you are willing to, you could give me remote access to your smile so I can take a look at the core/domain_objects response as you suggested.

**Comment by eelco2k** [comment]
Sorry I didn’t mention that they will release this firmware next week. I was one of the first because I had some other issues with the device. They already put the new firmware on my P1 device. 

So I guess next week the firmware will be published for every plugwise P1 owner.

**Comment by eelco2k** [comment]
@gruijter i will send you an e-mail with url and login credentials.

**Comment by gruijter** [comment]
Top 😀

Btw: Are you sure that you don't have some beta firmware, and that the 'old'  xml data will not be added in a final release version?

**Comment by gruijter** [comment]
v3.0.0 was just released as beta in the app store. Many thanks for helping out and testing during the development @eelco2k !
