### ISSUE TITLE
Ledring acts strange 

### ISSUE THREAD

**Issue by jaxc0402** [gruijter/com.plugwise.smile#8]
See pictures 👍 

While set max W to 8130 
My lering gets solid bleu (not 1/2) from around 2000 - 2500 W

![IMG_0934](https://user-images.githubusercontent.com/18361873/61866411-61960700-aed5-11e9-935f-ed65f5626e97.jpeg)
![IMG_0933](https://user-images.githubusercontent.com/18361873/61866412-61960700-aed5-11e9-8087-c4cabf7ccbf5.jpeg)

**Comment by gruijter** [comment]
v3.0.3  2019.07.26 Ledring production fix. This version is pending approval by Athom in the appstore.
