### ISSUE TITLE
Socket Hang Up

### ISSUE THREAD

**Issue by stofferr** [gruijter/com.plugwise.smile#9]
Hi I have a socket hang up since some time now.  The debug log file says every ~20 seconds:
- [managerdrivers] [smilep1][0] Poll error socket hang up 
The Smart meter app in the device list displays a red exclamation mark.
The Smart meter details page says  "Device is unavailable" and " socket hang up" 

I'm on Homey 2.5.1 (2.5.0 had the same issue)
Plugwise P1 app version 3.0.3

**Comment by gruijter** [comment]
Can you check if updating to 3.0.4 makes a difference? If not, can you give me remote access to your smile?

**Comment by stofferr** [comment]
I have a working aoolication since last Wednesday??? I cannot explain. Version 3.0.4 is also working. 

⁣Met vriendelijke groet,
Roger Stoffers ​

**Comment by gruijter** [comment]
mmh. Maybe something changed in your (wifi) network? I will close the issue for now, but feel free to open again if the issue returns.

**Comment by stofferr** [comment]
I remember now that I had zigbee issues solved with a hard power cycle. 2 minutes of no power also seem to have solved this one. 

⁣Met vriendelijke groet,
Roger Stoffers ​

**Comment by gruijter** [comment]
Ah, good to know! Thx for letting me know.

**Comment by wf-dekker** [comment]
Ok, I know this is a very old thread but I have the same issue now. It started when I added a new homey, the new homey kept disconnecting from smile p1 with “socket hang up” after about 12-24 hours but my old homey was still fine. I was thinking it was a homey issue so switch back after a few days to the old homey (turning the new one off) and now my old homey also has the issue. 
It may be something related to the WiFi but turning the smile p1 off and on again fixes it for a while. Restarting homey or network does not fix it. 
Any idea’s?
